// ─────────────────────────────────────────────
//  BOOK CHAPTERS DATA · 專書章節資料
//  Single source of truth for academic + publications pages.
//  Sorted: most recent first.
//  Edit this file to add a new chapter; pages auto-update.
// ─────────────────────────────────────────────
const chaptersData = [
  { year: 2026,
    title_zh: '台灣年金改革的危機和轉機',
    title_en: 'The Crisis and Turning Point of Taiwan\'s Pension Reform',
    authors_zh: '葉崇揚、陳芬苓、施世駿、古允文',
    authors_en: 'Yeh, C-Y., Chen, F-L., Shih, S-J. and Ku, Y-W.',
    src_zh: '收錄於葉崇揚、陳芬苓、施世駿、古允文（編著）《葬送的福利年（金）》。台北：巨流。',
    src_en: 'In Yeh, Chen, Shih &amp; Ku (eds.), <em>The Funeral of Welfare Pensions: Challenges and Solutions for Taiwan\'s Pension Reform</em>. Taipei: Chuliu.' },
  { year: 2026,
    title_zh: '年金市場化和金融化：福利市場與管制型福利國家的興起',
    title_en: 'Pension Marketisation and Financialisation: Welfare Markets and the Rise of Regulatory Welfare States',
    authors_zh: '葉崇揚、施世駿',
    authors_en: 'Yeh, C-Y. and Shih, S-J.',
    src_zh: '收錄於葉崇揚、陳芬苓、施世駿、古允文（編著）《葬送的福利年（金）》。台北：巨流。',
    src_en: 'In Yeh, Chen, Shih &amp; Ku (eds.), <em>The Funeral of Welfare Pensions</em>. Taipei: Chuliu.' },
  { year: 2025,
    title_zh: '老化與退休時間的國際比較',
    title_en: 'An International Comparison of Aging and Retirement Timing',
    authors_zh: '葉崇揚',
    authors_en: 'Yeh, C-Y.',
    src_zh: '收錄於古允文（編著）《法定老年及退休年齡之研討》，頁35–57。台北：國家衛生研究院。',
    src_en: 'In Ku, Y-W. (ed.), <em>Statutory Old-Age and Retirement Age</em>, pp. 35–57. Taipei: National Health Research Institutes.' },
  { year: 2023,
    title_zh: '第四篇‧社會變遷與應用：第十六章 社會變遷與全球化',
    title_en: 'Chapter 16: Social Change and Globalisation (Section IV)',
    authors_zh: '葉崇揚',
    authors_en: 'Yeh, C-Y.',
    src_zh: '收錄於陳芬苓（編著）《社會學》。台中：華格那。',
    src_en: 'In Chen, F-L. (ed.), <em>Sociology</em>. Taichung: Wagner.' },
  { year: 2023,
    title_zh: 'Active Labour Market Policies in East Asia',
    title_en: 'Active Labour Market Policies in East Asia',
    authors_zh: 'Hong, I., Yeh, C-Y. and Nahm, J.',
    authors_en: 'Hong, I., Yeh, C-Y. and Nahm, J.',
    src_zh: 'In <em>Handbook of Labour Market Policy in Advanced Democracies</em>, pp. 417–434. Cheltenham: Edward Elgar.',
    src_en: 'In <em>Handbook of Labour Market Policy in Advanced Democracies</em>, pp. 417–434. Cheltenham: Edward Elgar.' },
  { year: 2023,
    title_zh: 'Public opinion and social policy reform in East Asia',
    title_en: 'Public opinion and social policy reform in East Asia',
    authors_zh: 'Yeh, C-Y. and Hong, I.',
    authors_en: 'Yeh, C-Y. and Hong, I.',
    src_zh: 'In Misa Izuhara (ed.), <em>A Research Agenda for East Asian Social Policy</em>, pp. 63–84. Cheltenham: Edward Elgar.',
    src_en: 'In Misa Izuhara (ed.), <em>A Research Agenda for East Asian Social Policy</em>, pp. 63–84. Cheltenham: Edward Elgar.' },
  { year: 2022,
    title_zh: 'What makes old-age poverty in East Asian societies so high?',
    title_en: 'What makes old-age poverty in East Asian societies so high?',
    authors_zh: 'Ku, I., Lee, W., Abe, A., Mengbing, Z., Shi, L., Yeh, C-Y. and Kim, D.',
    authors_en: 'Ku, I., Lee, W., Abe, A., Mengbing, Z., Shi, L., Yeh, C-Y. and Kim, D.',
    src_zh: 'In Ku, I. and Saunders, P. (eds.), <em>Poverty and Inequality in East Asia</em>, pp. 196–220. Cheltenham: Edward Elgar.',
    src_en: 'In Ku, I. and Saunders, P. (eds.), <em>Poverty and Inequality in East Asia</em>, pp. 196–220. Cheltenham: Edward Elgar.' },
  { year: 2022,
    title_zh: 'An Increasing but Diverse Support for Social Investment: Public Opinion on Social Investment in the North East Asian Welfare Systems',
    title_en: 'An Increasing but Diverse Support for Social Investment',
    authors_zh: 'Hong, I., Yeh, C-Y., Lee, J. and Lue, J-D.',
    authors_en: 'Hong, I., Yeh, C-Y., Lee, J. and Lue, J-D.',
    src_zh: 'In Garritzmann, J., Häusermann, S., Palier, B. (eds.), <em>The World Politics of Social Investment</em> (Vol. II), pp. 259–284. Oxford: Oxford University Press.',
    src_en: 'In Garritzmann et al. (eds.), <em>The World Politics of Social Investment</em> (Vol. II), pp. 259–284. Oxford: Oxford University Press.' },
  { year: 2021,
    title_zh: '社會投資──源起、典範與批評（第二章）',
    title_en: 'Social Investment: Origins, Paradigms, and Critiques (Chapter 2)',
    authors_zh: '葉崇揚、古允文',
    authors_en: 'Yeh, C-Y. and Ku, Y-W.',
    src_zh: '收錄於《人口高齡化與社會福利──社會投資的反思》，頁27–42。台北：國家衛生研究院。',
    src_en: 'In <em>Population Aging and Social Welfare: Reflections on Social Investment</em>, pp. 27–42. Taipei: National Health Research Institutes.' },
  { year: 2020,
    title_zh: '台湾の第三章・制度の概要',
    title_en: 'Taiwan: Chapter 3 — Overview of the System',
    authors_zh: '孫瑩芯、施世駿、葉崇揚',
    authors_en: 'Sun, Y-X., Shih, S-J. and Yeh, C-Y.',
    src_zh: '收錄於上村泰裕（編著），《新世界の社会福祉（第7巻）：東アジア》，頁451–492。東京：旬報社。',
    src_en: 'In Yasuhiro Kamimura (ed.), <em>New World Social Welfare (Vol. 7): East Asia</em>, pp. 451–492. Tokyo: Junposha.' },
  { year: 2018,
    title_zh: '產業化？私有化？市場化？福利市場的興起',
    title_en: 'Industrialization? Privatization? Marketization? The Rise of Welfare Markets',
    authors_zh: '葉崇揚',
    authors_en: 'Yeh, C-Y.',
    src_zh: '收錄於古允文（主編），《醫療與福利服務產業化評估研究》，頁25–38。台北：國家衛生研究院。',
    src_en: 'In Ku, Y-W. (ed.), <em>Evaluating the Industrialization of Health and Welfare Services</em>, pp. 25–38. Taipei: National Health Research Institutes.' },
  { year: 2018,
    title_zh: '台灣所得分配惡化的政治經濟基礎：一個政治的解釋',
    title_en: 'The Political Economy of Income Distribution Deterioration in Taiwan: A Political Interpretation',
    authors_zh: '呂建德、葉崇揚',
    authors_en: 'Lue, J-D. and Yeh, C-Y.',
    src_zh: '收錄於許宗力（編著），《追尋社會國──社會正義之理論與制度實踐》。台北：台大出版中心。',
    src_en: 'In Hsu, T-L. (ed.), <em>In Search of the Social State: Theory and Institutional Practice of Social Justice</em>. Taipei: National Taiwan University Press.' },
  { year: 2018,
    title_zh: 'In-Work Poverty in three East Asian Welfare States',
    title_en: 'In-Work Poverty in three East Asian Welfare States',
    authors_zh: 'Yeh, C-Y. and Lue, J-D.',
    authors_en: 'Yeh, C-Y. and Lue, J-D.',
    src_zh: 'In Lohmann, H. and Marx, I. (eds.), <em>Handbook of Research on In-Work Poverty</em>, pp. 449–472. Cheltenham: Edward Elgar.',
    src_en: 'In Lohmann, H. and Marx, I. (eds.), <em>Handbook of Research on In-Work Poverty</em>, pp. 449–472. Cheltenham: Edward Elgar.' },
  { year: 2016,
    title_zh: '一個抉擇：台灣需要什麼樣的教育與技術形成體系',
    title_en: 'A Choice: What Education and Skill Formation System Does Taiwan Need',
    authors_zh: '葉崇揚',
    authors_en: 'Yeh, C-Y.',
    src_zh: '收錄於陳錦稷（編著），《新藍圖、新活路：台灣新經濟模式倡議》，頁92–117。台北：新境界文教基金會。',
    src_en: 'In Chen, C-J. (ed.), <em>New Blueprint, New Path: A Proposal for Taiwan\'s New Economic Model</em>, pp. 92–117. Taipei: New Frontier Foundation.' },
  { year: 2014,
    title_zh: 'Public-Private Pension Mix and Its Governance: Japan and Taiwan Compared',
    title_en: 'Public-Private Pension Mix and Its Governance: Japan and Taiwan Compared',
    authors_zh: 'Yeh, C-Y. and Shi, S-J.',
    authors_en: 'Yeh, C-Y. and Shi, S-J.',
    src_zh: 'In Mok, K-H. and Lau, M. (eds.), <em>Managing Social Change and Social Policy in Greater China</em>, pp. 170–190. London: Routledge.',
    src_en: 'In Mok, K-H. and Lau, M. (eds.), <em>Managing Social Change and Social Policy in Greater China</em>, pp. 170–190. London: Routledge.' },
  { year: 2012,
    title_zh: '台灣社會保障體系及其再分配效果',
    title_en: 'Taiwan\'s Social Protection System and Its Redistributive Effects',
    authors_zh: '呂建德、葉崇揚、陳昭榮',
    authors_en: 'Lue, J-D., Yeh, C-Y. and Chen, C-J.',
    src_zh: '收錄於《中國社會保障發展報告（2012）No. 5──社會保障與收入再分配》，頁211–233。北京：社會科學文獻出版社。',
    src_en: 'In <em>China Social Security Development Report (2012) No. 5: Social Security and Income Redistribution</em>, pp. 211–233. Beijing: Social Sciences Academic Press.' },
  { year: 2009,
    title_zh: '制度變遷的依變項問題：東亞年金體系的比較',
    title_en: 'The Dependent Variable Problem in Institutional Change: A Comparison of East Asian Pension Systems',
    authors_zh: '葉崇揚、呂建德',
    authors_en: 'Yeh, C-Y. and Lue, J-D.',
    src_zh: '收錄於李明政（編著），《新興福利國家與高齡化社會：學習與創新》，頁63–104。台北：松慧出版社。',
    src_en: 'In Lee, M-C. (ed.), <em>Emerging Welfare States and Aging Society: Learning and Innovation</em>, pp. 63–104. Taipei: Sung Hui.' },
];

// Render top-N book chapters into a `.ch-list` container.
function renderTopChapters(containerId, limit, lang) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const items = chaptersData.slice(0, limit);
  const html = items.map(c => {
    const title = lang === 'en' ? c.title_en : c.title_zh;
    const authors = lang === 'en' ? c.authors_en : c.authors_zh;
    const src = lang === 'en' ? c.src_en : c.src_zh;
    return `<article class="ch-row"><div class="y">${c.year}</div><div><h3>${title}</h3><div class="au">${authors}</div><div class="src">${src}</div></div></article>`;
  }).join('');
  container.insertAdjacentHTML('beforeend', html);
}
