// ─────────────────────────────────────────────
//  CONFERENCE PAPERS DATA · 研討會論文資料
//  Single source of truth — most recent first.
//  Edit this file to add a new conference paper; pages auto-update.
// ─────────────────────────────────────────────
const conferencesData = [
  { year: 2025,
    title_zh: 'Introduction: Digitalization, Precarious Work, and Welfare State in Asia',
    title_en: 'Introduction: Digitalization, Precarious Work, and Welfare State in Asia',
    authors: 'Lee, S., Au-Yeung, T. and Yeh, C-Y.',
    venue: 'Workshop "Digitalization, Precarious Work, and Welfare State in Asia", 12–13 Sep 2025, National Taipei University' },
  { year: 2025,
    title_zh: 'Work-Family Balance among Female Self-employed Workers in Japan and Taiwan',
    title_en: 'Work-Family Balance among Female Self-employed Workers in Japan and Taiwan',
    authors: 'Naka, S., Kamimura, Y. and Yeh, C-Y.',
    venue: 'Workshop "Digitalization, Precarious Work, and Welfare State in Asia", 12–13 Sep 2025, NTPU' },
  { year: 2025,
    title_zh: 'The Activation Turn or the Decline of Social Solidarity: Public Attitude towards Passive and Active Labour Market Policies in Taiwan',
    title_en: 'The Activation Turn or the Decline of Social Solidarity: Public Attitude towards Passive and Active Labour Market Policies in Taiwan',
    authors: 'Yeh, C-Y.',
    venue: 'Workshop "Digitalization, Precarious Work, and Welfare State in Asia", 12–13 Sep 2025, NTPU' },
  { year: 2025,
    title_zh: 'Cumulating Precarity in Gig Economy: The Precariatization of Single Mothers in Taiwan',
    title_en: 'Cumulating Precarity in Gig Economy: The Precariatization of Single Mothers in Taiwan',
    authors: 'Hung, H-F., Lee, S-F., Huang, F-Y. and Yeh, C-Y.',
    venue: 'Workshop "Digitalization, Precarious Work, and Welfare State in Asia", 12–13 Sep 2025, NTPU' },
  { year: 2025,
    title_zh: 'Who are Deserving Poor in Taiwan and Korea: A Conjoint Experiment Survey',
    title_en: 'Who are Deserving Poor in Taiwan and Korea: A Conjoint Experiment Survey',
    authors: 'Yeh, C-Y., Huang, F-Y., Wang, J., Hong, I., Ku, Y-W., Ku, I., Kim, E. and Chang, Y-F.',
    venue: '2025 ESPAnet Annual Conference, 27–29 Aug 2025, University of Milan, Italy' },
  { year: 2025,
    title_zh: 'Is More Choice the Right Choice? Exploring Public Preferences for Encouraging IRA Savings through a Randomized Survey Experiment',
    title_en: 'Is More Choice the Right Choice? Exploring Public Preferences for Encouraging IRA Savings through a Randomized Survey Experiment',
    authors: 'Yeh, C-Y., Huang, F-Y. and Ku, Y-W.',
    venue: '2025 SPA-EASP Joint Annual Conference, 2–4 Jul 2025, University of York, UK' },
  { year: 2025,
    title_zh: 'Population Aging, Pension Sustainability, and Public Opinion: Does Better Information Lead to Greater Reform Endorsement?',
    title_en: 'Population Aging, Pension Sustainability, and Public Opinion: Does Better Information Lead to Greater Reform Endorsement?',
    authors: 'Yeh, C-Y.',
    venue: '2025 SPA-EASP Joint Annual Conference, 2–4 Jul 2025, University of York, UK' },
  { year: 2025,
    title_zh: 'Who are Deserving Poor in Taiwan and Korea: A Conjoint Experiment Survey',
    title_en: 'Who are Deserving Poor in Taiwan and Korea: A Conjoint Experiment Survey',
    authors: 'Yeh, C-Y., Huang, F-Y., Wang, J., Hong, I., Ku, Y-W., Ku, I., Kim, E. and Chang, Y-F.',
    venue: '2025 SPA-EASP Joint Annual Conference, 2–4 Jul 2025, University of York, UK' },
  { year: 2024,
    title_zh: 'Crafting a Welfare Market: The Rise of the Market-based Homecare in Taiwan',
    title_en: 'Crafting a Welfare Market: The Rise of the Market-based Homecare in Taiwan',
    authors: 'Yang, H-H. and Yeh, C-Y.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2024,
    title_zh: 'Asset-based Welfare Regime and Public Pension Reforms in East Asia',
    title_en: 'Asset-based Welfare Regime and Public Pension Reforms in East Asia',
    authors: 'Ku, I., Yeh, C-Y. et al.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2024,
    title_zh: 'The Emergence of the Two-Tier Bismarckian Pension Model in Taiwan',
    title_en: 'The Emergence of the Two-Tier Bismarckian Pension Model in Taiwan',
    authors: 'Yeh, C-Y.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2024,
    title_zh: 'To Choose or Not to Choose: Public Preferences for Pension Choice in Taiwan',
    title_en: 'To Choose or Not to Choose: Public Preferences for Pension Choice in Taiwan',
    authors: 'Huang, F-Y., Yeh, C-Y. and Ku, Y-W.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2024,
    title_zh: 'Cumulating Precarity in Platform Economy: The Case of Single Mothers',
    title_en: 'Cumulating Precarity in Platform Economy: The Case of Single Mothers',
    authors: 'Hung, H-F., Lee, S-F., Huang, F-Y. and Yeh, C-Y.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2024,
    title_zh: 'Who are Deserving Poor in Taiwan: A Conjoint Experiment Survey',
    title_en: 'Who are Deserving Poor in Taiwan: A Conjoint Experiment Survey',
    authors: 'Ku, Y-W., Yeh, C-Y., Huang, F-Y. and Chang, Y-F.',
    venue: '2024 EASP Annual Conference, Kyoto, Japan' },
  { year: 2023,
    title_zh: 'Pension Retrenchment in Taiwan: How the Politics of Pension Retrenchment was Managed',
    title_en: 'Pension Retrenchment in Taiwan: How the Politics of Pension Retrenchment was Managed',
    authors: 'Yeh, C-Y. and Huang, F-Y.',
    venue: 'Conference of National Pension Association in Korea, 3 Dec 2023, Seoul, Korea' },
  { year: 2023,
    title_zh: 'The Politics of the 2018 Pension Retrenchment in Taiwan: Loud and Noisy, but Credit-Claiming',
    title_en: 'The Politics of the 2018 Pension Retrenchment in Taiwan: Loud and Noisy, but Credit-Claiming',
    authors: 'Yeh, C-Y., Liu, Y-S. and Ku, Y-W.',
    venue: '2023 EASP Annual Conference, 14–15 Sep 2023, Sydney, Australia' },
  { year: 2022,
    title_zh: 'Public Attitude towards Economic Relief Programme during the Covid-19 Pandemic in Taiwan',
    title_en: 'Public Attitude towards Economic Relief Programme during the Covid-19 Pandemic in Taiwan',
    authors: 'Yeh, C-Y., Tsai, P-Y. and Ku, Y-W.',
    venue: 'Workshop "Social Innovation and Social Cleavages in East Asian Welfare States during and after the Covid-19 Pandemic", 2–3 Jul 2022, Soochow University, Taipei' },
  { year: 2022,
    title_zh: '女性勞動參與率：社會投資有用嗎？',
    title_en: 'Female Labour Force Participation: Does Social Investment Work?',
    authors_zh: '唐德融、葉崇揚',
    authors_en: 'Tang, D-R. and Yeh, C-Y.',
    venue_zh: '2022 台灣社會福利學會年會，國立中正大學，嘉義',
    venue_en: '2022 Annual Conference of Taiwan Social Welfare Association, National Chung Cheng University, Chiayi' },
  { year: 2021,
    title_zh: 'AI 社會下的數位創新與福利國家',
    title_en: 'Digital Innovation and the Welfare State in the AI Society',
    authors_zh: '葉崇揚',
    authors_en: 'Yeh, C-Y.',
    venue_zh: '2021 台灣社會福利學會年會暨國際研討會，2021年5月14日，東吳大學，台北',
    venue_en: '2021 International Annual Conference of Taiwan Social Welfare Association, 14 May 2021, Soochow University, Taipei' },
  { year: 2021,
    title_zh: 'The Politics of the 2018 Pension Reform in Taiwan: Class, Generation, or Party?',
    title_en: 'The Politics of the 2018 Pension Reform in Taiwan: Class, Generation, or Party?',
    authors: 'Yeh, C-Y. and Tsai, M-C.',
    venue: '2021 International Conference of Social Welfare Association of Taiwan, 15 May 2021, Soochow University, Taipei' },
];

// Render top-N conference papers into a `.c-list` container.
function renderTopConferences(containerId, limit, lang) {
  const container = document.getElementById(containerId);
  if (!container) return;
  const items = conferencesData.slice(0, limit);
  const html = items.map(c => {
    // For English-titled entries (most are English-language conferences), always show English.
    // For entries with explicit Chinese title (台灣 conferences), show language-appropriate.
    const title = (lang === 'en') ? (c.title_en || c.title_zh) : (c.title_zh || c.title_en);
    const authors = c.authors || (lang === 'en' ? (c.authors_en || c.authors_zh) : (c.authors_zh || c.authors_en));
    const venue = c.venue || (lang === 'en' ? (c.venue_en || c.venue_zh) : (c.venue_zh || c.venue_en));
    return `<article class="c-row"><div class="y">${c.year}</div><div><h3>${title}</h3><div class="au">${authors}</div><div class="v">${venue}</div></div></article>`;
  }).join('');
  container.insertAdjacentHTML('beforeend', html);
}
