// ─────────────────────────────────────────────
//  PHOTOGRAPHY DATA · 寫真資料
//  num:    照片編號（001–043）
//  themes: 'street' | 'harugasumi' | 'aoarashi' | 'kouyou' | 'yukiakari' | 'kaiyou' | 'xpan' | 'misc'
//  shape:  'landscape' | 'portrait' | 'square' | 'xpan'
//  title_jp / title_en / title_zh — 三語名稱
//  haiku_jp / haiku_en / haiku_zh — 三行俳句式說明
//
//  ※ 名稱與俳句皆由作者撰寫，可隨時修改。
// ─────────────────────────────────────────────
const photoData = [

  // ── 春信 SPRING ──
  { num: '136', src: 'images/photography/img_9078.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '春の家族', title_en: 'Spring Family', title_zh: '春日家族',
    haiku_jp: '桜の下／三世代の／春の朝',
    haiku_en: 'beneath the cherry — / three generations / one spring morning',
    haiku_zh: '櫻花樹下／三代人／春之晨' },
  { num: '056', src: 'images/photography/dscf3093.jpg', themes: ['harugasumi','xpan'], shape: 'xpan',
    title_jp: '山桜', title_en: 'Mountain Cherry', title_zh: '山櫻',
    haiku_jp: '山桜／闇の中にも／光あり',
    haiku_en: 'mountain cherry — / even in the darkness / there is light',
    haiku_zh: '山櫻／黑暗之中／也有光' },
  { num: '145', src: 'images/photography/l1002835_3.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '紅椿落つ', title_en: 'Fallen Camellias', title_zh: '紅椿落',
    haiku_jp: '紅椿／苔に落ちては／春の音',
    haiku_en: 'crimson camellia / falling onto moss — / the sound of spring',
    haiku_zh: '紅椿／落於青苔／春之音' },
  { num: '118', src: 'images/photography/img_0394.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '夜桜', title_en: 'Night Cherry', title_zh: '夜櫻',
    haiku_jp: '春の月／桜の花を／見守りぬ',
    haiku_en: 'spring moon / watches over / the cherry blossoms',
    haiku_zh: '春月／守望著／櫻花' },
  { num: '103', src: 'images/photography/dscf7924_2.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '夕桜', title_en: 'Evening Cherry', title_zh: '夕櫻',
    haiku_jp: '夕べの陽／枝に乗りつつ／花染まる',
    haiku_en: 'evening sun / climbing onto the branch / dyes the blossoms',
    haiku_zh: '黃昏的陽光／攀上枝頭／染上花瓣' },
  { num: '096', src: 'images/photography/dscf7075_4.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '河津桜', title_en: 'Kawazu Sakura', title_zh: '河津櫻',
    haiku_jp: '朝の道／桜のトンネル／人ふたり',
    haiku_en: 'morning path — / a tunnel of cherry blossoms / two people walking',
    haiku_zh: '晨之道／櫻花隧道／兩個人' },
  { num: '042', src: 'images/photography/img_9798.jpg', themes: ['harugasumi'], shape: 'landscape',
    title_jp: '花の道', title_en: 'Path of Blossoms', title_zh: '花徑',
    haiku_jp: '一人歩く／花の道は／もう何度目',
    haiku_en: 'walking alone — / how many times now / this path of blossoms',
    haiku_zh: '一人走過／這條花徑／已是第幾回' },
  { num: '028', src: 'images/photography/dscf8885_1.jpg', year: 2025, themes: ['harugasumi'], shape: 'landscape',
    title_jp: '春暁', title_en: 'Spring Dawn', title_zh: '春曉',
    haiku_jp: '春暁や／淡き光の／差し始む',
    haiku_en: 'spring dawn — / a tender light / begins to enter',
    haiku_zh: '春曉／淡淡的光／緩緩傾入' },
  { num: '026', src: 'images/photography/dscf8423_1.jpg', year: 2026, themes: ['harugasumi'], shape: 'landscape',
    title_jp: '春霞', title_en: 'Spring Haze', title_zh: '春霞',
    haiku_jp: '春霞／山の輪郭が／溶けてゆく',
    haiku_en: 'spring haze / the mountain\'s outline / dissolves',
    haiku_zh: '春霞／山的輪廓／漸漸消融' },
  { num: '019', src: 'images/photography/dscf6846_1.jpg', year: 2025, themes: ['harugasumi'], shape: 'landscape',
    title_jp: '花影', title_en: 'Blossom Shadow', title_zh: '花影',
    haiku_jp: '花の影／道に揺らぐ／春の風',
    haiku_en: 'shadow of blossoms / trembling on the path / a spring breeze',
    haiku_zh: '花影／在道上搖曳／春風' },
  { num: '016', src: 'images/photography/dscf5975_1.jpg', year: 2025, themes: ['harugasumi'], shape: 'landscape',
    title_jp: '花霞', title_en: 'Blossom Mist', title_zh: '花霞',
    haiku_jp: '山桜／一面の白に／朝の霞',
    haiku_en: 'mountain cherry / a whole hillside of white / wrapped in morning mist',
    haiku_zh: '山櫻／一片皎白／晨霞' },
  { num: '015', src: 'images/photography/dscf5542_2.jpg', year: 2025, themes: ['harugasumi'], shape: 'landscape',
    title_jp: '城南の枝垂梅', title_en: 'Weeping Plum at Jōnan-gū', title_zh: '城南宮的枝垂梅',
    haiku_jp: '春雨や／城南の枝垂梅／源氏の夢',
    haiku_en: 'spring rain falls — / on Jōnan\'s weeping plum / a dream from Genji',
    haiku_zh: '春雨／城南枝垂梅／源氏之夢' },
  { num: '003', src: 'images/photography/2019-12-22_09-24-27.jpg', year: 2019, themes: ['harugasumi'], shape: 'landscape',
    title_jp: 'しだれ桜', title_en: 'Weeping Cherry', title_zh: '枝垂櫻',
    haiku_jp: '枝垂れて／重き花房の／春の朝',
    haiku_en: 'weeping low / the heavy clusters of bloom / in spring morning',
    haiku_zh: '枝垂／繁花重重／春之晨' },
  { num: '037', src: 'images/photography/img_5427.jpg', year: 2023, themes: ['harugasumi'], shape: 'square',
    title_jp: '春陰', title_en: 'Spring Shade', title_zh: '春陰',
    haiku_jp: '桜陰／静かに息を／整える',
    haiku_en: 'in the cherry\'s shade / I quietly compose / my breath',
    haiku_zh: '櫻蔭／靜靜地調整／呼吸' },
  { num: '032', src: 'images/photography/dscf9795_xd3.jpg', year: 2026, themes: ['harugasumi'], shape: 'square',
    title_jp: '桜雨', title_en: 'Cherry Rain', title_zh: '櫻雨',
    haiku_jp: '雨上がり／花びらの色／濃くなりぬ',
    haiku_en: 'after the rain / the petals deepen / their color',
    haiku_zh: '雨後／花瓣的顏色／更深一層' },
  { num: '025', src: 'images/photography/dscf8356_3.jpg', year: 2025, themes: ['harugasumi'], shape: 'square',
    title_jp: '春の野', title_en: 'Spring Meadow', title_zh: '春野',
    haiku_jp: '春の野や／何もせぬまま／日が暮れる',
    haiku_en: 'spring meadow — / doing nothing at all / the sun goes down',
    haiku_zh: '春野／無所事事／日已西斜' },

  // ── 青嵐 SUMMER ──
  { num: '035', src: 'images/photography/img_3506.jpg', year: 2024, themes: ['aoarashi'], shape: 'square',
    title_jp: '琉璃光院', title_en: 'Ruriko-in', title_zh: '琉璃光院',
    haiku_jp: '水の音や／楓の影をゆく／鯉ひとつ',
    haiku_en: 'sound of water — / through maple shadows / one quiet koi glides',
    haiku_zh: '水聲／穿過楓影／一尾鯉魚靜行' },
  { num: '132', src: 'images/photography/img_4355.jpg', themes: ['aoarashi'], shape: 'landscape',
    title_jp: '麦畑', title_en: 'Wheat Field', title_zh: '麥田',
    haiku_jp: '麦の穂や／空に向かって／夏を呼ぶ',
    haiku_en: 'ears of wheat — / lifting toward the sky / they call for summer',
    haiku_zh: '麥穗／向著天空／呼喚夏天' },
  { num: '058', src: 'images/photography/dscf3375_1.jpg', themes: ['aoarashi'], shape: 'landscape',
    title_jp: '蓮華', title_en: 'Lotus Flower', title_zh: '蓮華',
    haiku_jp: '緑の中／一つだけの／薄い花',
    haiku_en: 'in all the green — / one single / pale flower',
    haiku_zh: '一片綠中／僅有一朵／淡淡的花' },
  { num: '051', src: 'images/photography/dscf2491_9.jpg', themes: ['aoarashi'], shape: 'landscape',
    title_jp: '蓮池', title_en: 'Lotus Pond', title_zh: '蓮池',
    haiku_jp: '蓮の葉や／鯉の朱色が／差し込みぬ',
    haiku_en: 'lotus leaves — / a koi\'s vermilion / slips between',
    haiku_zh: '蓮葉之間／鯉魚的朱色／悄然穿過' },
  { num: '049', src: 'images/photography/dscf2192_4.jpg', themes: ['aoarashi'], shape: 'landscape',
    title_jp: '紅蓮', title_en: 'Pink Lotus', title_zh: '紅蓮',
    haiku_jp: '夏の池／薄紅の花／空に向く',
    haiku_en: 'summer pond — / a pale crimson flower / faces the sky',
    haiku_zh: '夏之池／淡紅的花／面向天空' },
  { num: '036', src: 'images/photography/img_3507.jpg', year: 2024, themes: ['aoarashi'], shape: 'landscape',
    title_jp: '涼風', title_en: 'Cool Breeze', title_zh: '涼風',
    haiku_jp: '縁側に／涼風通れば／夏の昼',
    haiku_en: 'across the veranda / a cool breeze passes — / summer noon',
    haiku_zh: '緣側／涼風吹過／夏之午' },
  { num: '005', src: 'images/photography/dscf8410_xd3.jpg', year: 2025, themes: ['aoarashi'], shape: 'landscape',
    title_jp: '緑陰', title_en: 'Verdant Canopy', title_zh: '綠蔭',
    haiku_jp: '木漏れ日や／緑の中の／夏の昼',
    haiku_en: 'sun through leaves — / inside the green / a summer noon',
    haiku_zh: '木漏日／在綠意之中／夏日午' },
  { num: '102', src: 'images/photography/dscf7791.jpg', themes: ['aoarashi'], shape: 'portrait',
    title_jp: '草の露', title_en: 'Dew on Grass', title_zh: '草上之露',
    haiku_jp: '草の先／露ひとつぶ／落ちぬまま',
    haiku_en: 'tip of a grass blade — / one single dewdrop / yet to fall',
    haiku_zh: '草尖／一滴露珠／尚未落下' },

  // ── 紅葉 AUTUMN ──
  { num: '097', src: 'images/photography/dscf7154_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '白と紅', title_en: 'White and Crimson', title_zh: '白與紅',
    haiku_jp: '白き樺／紅葉の中に／立ち尽くす',
    haiku_en: 'a white birch / standing within the crimson — / unmoving',
    haiku_zh: '白色樺樹／在紅葉之中／靜靜佇立' },
  { num: '080', src: 'images/photography/dscf4963_2.jpg', themes: ['sansui','xpan'], shape: 'xpan',
    title_jp: '黄金の壁', title_en: 'Golden Wall', title_zh: '金壁',
    haiku_jp: '霧の中／山肌だけが／黄金なり',
    haiku_en: 'inside the mist — / only the mountain\'s face / is golden',
    haiku_zh: '霧之中／僅山的肌膚／是金色的' },
  { num: '076', src: 'images/photography/dscf4835_1.jpg', themes: ['kouyou','xpan'], shape: 'xpan',
    title_jp: '梓川', title_en: 'Azusa River', title_zh: '梓川',
    haiku_jp: '清流や／落葉松の影／秋深む',
    haiku_en: 'clear river — / shadows of larch / deepen the autumn',
    haiku_zh: '清流／落葉松的影／秋意更濃' },
  { num: '062', src: 'images/photography/dscf3783_3.jpg', themes: ['kouyou','xpan'], shape: 'xpan',
    title_jp: '森の歌', title_en: 'Forest Song', title_zh: '森之歌',
    haiku_jp: '黄金の／森が静かに／歌い出す',
    haiku_en: 'a golden forest / quietly / begins to sing',
    haiku_zh: '金黃的森林／靜靜地／開始歌唱' },
  { num: '060', src: 'images/photography/dscf3771_2.jpg', themes: ['kouyou','xpan'], shape: 'xpan',
    title_jp: '錦秋', title_en: 'Brocade Autumn', title_zh: '錦秋',
    haiku_jp: '黄金と／紅と橙の／森の中',
    haiku_en: 'gold and / crimson and orange — / inside the forest',
    haiku_zh: '金與／紅與橙／森林之中' },
  { num: '150', src: 'images/photography/l1006500_6.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '紅葉路', title_en: 'Maple Lane', title_zh: '紅葉之路',
    haiku_jp: '紅葉の／路の先には／何があるか',
    haiku_en: 'down the maple lane — / what lies / at its end?',
    haiku_zh: '紅葉之路／盡頭／是什麼呢' },
  { num: '116', src: 'images/photography/dscf9904_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '見上げて', title_en: 'Looking Up', title_zh: '仰望',
    haiku_jp: '見上げれば／紅葉の天蓋／世界変わる',
    haiku_en: 'looking up — / a canopy of crimson / the world changes',
    haiku_zh: '抬頭一望／紅葉如天蓋／世界已改變' },
  { num: '107', src: 'images/photography/dscf8119_xd2s_3.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '寺の秋', title_en: 'Temple Autumn', title_zh: '寺之秋',
    haiku_jp: '紅葉と／障子の白と／秋の夕',
    haiku_en: 'crimson leaves / paper screens of white / autumn evening',
    haiku_zh: '紅葉／白紙障子／秋之夕' },
  { num: '105', src: 'images/photography/dscf7956_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '黄金の樹', title_en: 'Golden Tree', title_zh: '金樹',
    haiku_jp: '黄金の／枝に陽が当たり／散る紅葉',
    haiku_en: 'on the golden bough — / the sun lights, then / scatters the leaves',
    haiku_zh: '金黃的枝／陽光照耀／落葉飛散' },
  { num: '095', src: 'images/photography/dscf7056_5.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '深紅', title_en: 'Deep Crimson', title_zh: '深紅',
    haiku_jp: '紅葉の／その中に隠す／緑あり',
    haiku_en: 'within the maples — / hidden / there is green',
    haiku_zh: '紅葉之中／藏著／點點翠綠' },
  { num: '094', src: 'images/photography/dscf7029_3.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '錦織', title_en: 'Woven Brocade', title_zh: '織錦',
    haiku_jp: '紅葉の／一面織りなす／秋深し',
    haiku_en: 'leaves of autumn / weaving an entire surface — / autumn deepens',
    haiku_zh: '紅葉／織就整片／秋意深沉' },
  { num: '093', src: 'images/photography/dscf7012_6.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '錦の山', title_en: 'Brocade Slope', title_zh: '錦山',
    haiku_jp: '山肌や／紅黄緑の／三色織り',
    haiku_en: 'mountain face — / crimson, gold, and green / woven together',
    haiku_zh: '山的肌膚／紅黃綠／三色相織' },
  { num: '092', src: 'images/photography/dscf7007_4.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '紅の嵐', title_en: 'Crimson Storm', title_zh: '紅葉之嵐',
    haiku_jp: '紅の中／白き枝々／秋の咆哮',
    haiku_en: 'inside the crimson — / pale branches / autumn\'s roar',
    haiku_zh: '紅葉之中／蒼白的枝椏／秋之咆哮' },
  { num: '091', src: 'images/photography/dscf6729_4.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '紅の連', title_en: 'Crimson Cluster', title_zh: '紅葉相連',
    haiku_jp: '一葉ずつ／重なり合いて／紅の海',
    haiku_en: 'leaf upon leaf / piling up / a sea of crimson',
    haiku_zh: '一片片／層層相疊／紅之海' },
  { num: '090', src: 'images/photography/dscf6714_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '渡し舟', title_en: 'Ferry Boat', title_zh: '渡舟',
    haiku_jp: '紅葉の下／一艘の舟が／川を行く',
    haiku_en: 'beneath the maples / a single boat / crosses the river',
    haiku_zh: '紅葉之下／一葉小舟／橫渡川面' },
  { num: '088', src: 'images/photography/dscf6313_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '嵐山', title_en: 'Arashiyama', title_zh: '嵐山',
    haiku_jp: '紅の屋根／川辺に座る／秋の人',
    haiku_en: 'crimson canopy — / by the river sits / one autumn person',
    haiku_zh: '紅葉如蓋／坐於河邊／秋之人' },
  { num: '086', src: 'images/photography/dscf5423_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '燃ゆる山', title_en: 'Burning Slope', title_zh: '燃燒的山',
    haiku_jp: '山肌に／橙の火が／走る',
    haiku_en: 'across the mountain — / orange fire / runs',
    haiku_zh: '山的肌膚／橙色之火／奔走' },
  { num: '085', src: 'images/photography/dscf5421_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '落葉松', title_en: 'Larch Forest', title_zh: '落葉松',
    haiku_jp: '夕闇に／落葉松だけが／燃え立てり',
    haiku_en: 'in the dusk — / only the larches / are still burning',
    haiku_zh: '暮色之中／只有落葉松／仍在燃燒' },
  { num: '084', src: 'images/photography/dscf5389_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '黄金の枝', title_en: 'Golden Bough', title_zh: '金枝',
    haiku_jp: '黄金の／枝先のかすか／光あり',
    haiku_en: 'a golden branch — / a faint light / on its very tip',
    haiku_zh: '金枝／其尖端／微光淡淡' },
  { num: '083', src: 'images/photography/dscf5110_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '河と松', title_en: 'River and Larch', title_zh: '河與松',
    haiku_jp: '川の水／松の黄金を／受け止む',
    haiku_en: 'the river\'s water / receives the larch\'s / golden hue',
    haiku_zh: '河水／承接著松的／金黃' },
  { num: '082', src: 'images/photography/dscf5082_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '草紅葉', title_en: 'Crimson Grass', title_zh: '草紅葉',
    haiku_jp: '草紅葉／山霧立ちて／秋の朝',
    haiku_en: 'crimson grass — / mountain mist rises / autumn morning',
    haiku_zh: '草紅／山霧升起／秋之晨' },
  { num: '081', src: 'images/photography/dscf5073_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '白樺', title_en: 'White Birch', title_zh: '白樺',
    haiku_jp: '白樺の／影が水面に／揺れる秋',
    haiku_en: 'shadows of white birch / tremble on the water — / autumn',
    haiku_zh: '白樺的影／在水面搖曳／秋' },
  { num: '079', src: 'images/photography/dscf4939_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '大正池', title_en: 'Taishō Pond', title_zh: '大正池',
    haiku_jp: '池の底／石の数まで／秋なる',
    haiku_en: 'bottom of the pond — / down to the count of stones / autumn',
    haiku_zh: '池底／連石頭的數量／都是秋' },
  { num: '077', src: 'images/photography/dscf4851_5.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '岳と松', title_en: 'Peak and Larch', title_zh: '岳與松',
    haiku_jp: '岩の山／落葉松燃え／秋の午後',
    haiku_en: 'rocky peak — / burning larch / autumn afternoon',
    haiku_zh: '岩山／燃燒的落葉松／秋之午' },
  { num: '075', src: 'images/photography/dscf4733_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '鏡池', title_en: 'Mirror Pond', title_zh: '鏡池',
    haiku_jp: '池に立つ／小さき鳥居と／秋の影',
    haiku_en: 'standing in the pond — / a small torii / and autumn shadow',
    haiku_zh: '池中／小小鳥居／秋之影' },
  { num: '071', src: 'images/photography/dscf4208_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '秋の沼', title_en: 'Autumn Marsh', title_zh: '秋沼',
    haiku_jp: '黄金の／木立に風が／吹く沼地',
    haiku_en: 'a golden grove — / wind passes / through the marsh',
    haiku_zh: '金黃的林／風吹過／沼澤' },
  { num: '068', src: 'images/photography/dscf4001_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '映る秋', title_en: 'Reflected Autumn', title_zh: '映秋',
    haiku_jp: '湖の上／山も雲も／秋になる',
    haiku_en: 'on the lake — / mountain and cloud / both become autumn',
    haiku_zh: '湖面之上／山與雲／皆成秋色' },
  { num: '061', src: 'images/photography/dscf3783_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '黄葉', title_en: 'Yellow Leaves', title_zh: '黃葉',
    haiku_jp: '黄色の／枝の重なりに／秋深し',
    haiku_en: 'layered yellow — / branch on branch / autumn deepens',
    haiku_zh: '黃色／層疊的枝椏／秋意已深' },
  { num: '059', src: 'images/photography/dscf3682_2.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '湖鏡', title_en: 'Lake Mirror', title_zh: '湖鏡',
    haiku_jp: '湖鏡や／秋の色彩を／反映せり',
    haiku_en: 'mirror of the lake — / reflecting / autumn\'s colors',
    haiku_zh: '湖如鏡／映出／秋之色彩' },
  { num: '055', src: 'images/photography/dscf2858_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '秋の白', title_en: 'Autumn White', title_zh: '秋之白',
    haiku_jp: '紅の葉と／白い瀑布と／秋の山',
    haiku_en: 'crimson leaves / a white waterfall / mountain in autumn',
    haiku_zh: '紅葉／白瀑／秋之山' },
  { num: '054', src: 'images/photography/dscf2844_1.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '滝紅葉', title_en: 'Maple by Falls', title_zh: '紅葉之瀑',
    haiku_jp: '滝の音／紅葉の中を／流れゆく',
    haiku_en: 'sound of the falls / runs through / the autumn leaves',
    haiku_zh: '瀑布之聲／穿過紅葉／流淌而下' },
  { num: '043', src: 'images/photography/img_9805.jpg', themes: ['kouyou'], shape: 'landscape',
    title_jp: '黄昏', title_en: 'Twilight', title_zh: '黃昏',
    haiku_jp: '黄昏や／紅葉に染まる／山の影',
    haiku_en: 'twilight — / dyed in autumn leaves / the mountain\'s shadow',
    haiku_zh: '黃昏／染上紅葉／山之影' },
  { num: '010', src: 'images/photography/dscf3424_1.jpg', year: 2025, themes: ['kouyou'], shape: 'landscape',
    title_jp: '朱の道', title_en: 'Crimson Path', title_zh: '朱徑',
    haiku_jp: '紅の／落ち葉踏みしめ／秋の朝',
    haiku_en: 'crimson — / treading on fallen leaves / autumn morning',
    haiku_zh: '紅色／踩過落葉／秋晨' },
  { num: '009', src: 'images/photography/dscf2136_2.jpg', year: 2025, themes: ['kouyou'], shape: 'landscape',
    title_jp: '秋風', title_en: 'Autumn Wind', title_zh: '秋風',
    haiku_jp: '秋風や／木立の中の／透き光',
    haiku_en: 'autumn wind — / between the trees / a translucent light',
    haiku_zh: '秋風／林中／透光' },
  { num: '002', src: 'images/photography/1575909151701_original.jpg', year: 2017, themes: ['kouyou'], shape: 'landscape',
    title_jp: '葉影', title_en: 'Maple Shadows', title_zh: '葉影',
    haiku_jp: '葉と影／重なる枝の／秋の闇',
    haiku_en: 'leaf and shadow / on the layered branches — / autumn dusk',
    haiku_zh: '葉與影／在重疊的枝上／秋之暗' },
  { num: '089', src: 'images/photography/dscf6594_29.jpg', themes: ['kouyou'], shape: 'square',
    title_jp: '紅の枝', title_en: 'Crimson Branch', title_zh: '紅枝',
    haiku_jp: '小さき葉／群れて流れる／秋の風',
    haiku_en: 'small leaves / gather and flow — / autumn wind',
    haiku_zh: '小小的葉／群聚而流／秋風' },
  { num: '008', src: 'images/photography/dscf1466_3.jpg', year: 2025, themes: ['kouyou'], shape: 'square',
    title_jp: '紅葉', title_en: 'Crimson Leaf', title_zh: '紅葉',
    haiku_jp: '紅葉や／一葉ひとひら／落ちゆけり',
    haiku_en: 'autumn leaves — / one by one, leaf by leaf / falling away',
    haiku_zh: '紅葉／一葉一葉／飄然而落' },

  // ── 雪明 WINTER ──
  { num: '012', src: 'images/photography/dscf4933_6.jpg', year: 2025, themes: ['yukiakari'], shape: 'landscape',
    title_jp: '静寂', title_en: 'Stillness', title_zh: '寂靜',
    haiku_jp: '静寂や／冬の窓辺に／光積む',
    haiku_en: 'stillness — / piling on the winter window / a thin light',
    haiku_zh: '寂靜／積在冬窗邊／微光淡淡' },
  { num: '165', src: 'images/photography/dscf4884_22.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '雪夜', title_en: 'Snow Night', title_zh: '雪夜',
    haiku_jp: '雪降りて／枯れ枝の中に／青き光',
    haiku_en: 'snow falling — / inside the bare branches / a blue light',
    haiku_zh: '雪降／枯枝之中／有青色之光' },
  { num: '166', src: 'images/photography/dscf4890_1.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '光の柱', title_en: 'Pillars of Light', title_zh: '光柱',
    haiku_jp: '雪の中／光の柱が／樹を照らす',
    haiku_en: 'within the snow / pillars of light / illumine the tree',
    haiku_zh: '雪中／光的柱／照亮樹梢' },
  { num: '087', src: 'images/photography/dscf5794_1.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '雪の波', title_en: 'Snow Waves', title_zh: '雪之波',
    haiku_jp: '青き雪／何の足跡も／残らぬ',
    haiku_en: 'blue snow — / no footprint / remains',
    haiku_zh: '藍色之雪／無一足跡／留下' },
  { num: '078', src: 'images/photography/dscf4871_2.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '柿と雪', title_en: 'Persimmon and Snow', title_zh: '柿與雪',
    haiku_jp: '柿の実／雪の降る中／落ちぬまま',
    haiku_en: 'persimmons — / through the falling snow / refusing to fall',
    haiku_zh: '柿之實／在落雪之中／不肯墜下' },
  { num: '074', src: 'images/photography/dscf4495_1.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '冬日和', title_en: 'A Winter Day', title_zh: '冬日',
    haiku_jp: '冬の湖／霊峰の前で／子は遊ぶ',
    haiku_en: 'winter lake — / before the sacred peak / a child plays',
    haiku_zh: '冬之湖／靈峰之前／孩童嬉戲' },
  { num: '072', src: 'images/photography/dscf4303_2.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '凍る湖', title_en: 'Frozen Lake', title_zh: '凍湖',
    haiku_jp: '凍る湖／霊峰浮かぶ／紫の朝',
    haiku_en: 'frozen lake — / the sacred peak floats / in violet morning',
    haiku_zh: '凍湖／靈峰浮現／紫色之晨' },
  { num: '050', src: 'images/photography/dscf2256.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '青き納屋', title_en: 'Blue Barn', title_zh: '藍納屋',
    haiku_jp: '青き屋根／雪原の上／冬の青',
    haiku_en: 'blue roof — / above the snow plain / winter blue',
    haiku_zh: '青色屋頂／雪原之上／冬之藍' },
  { num: '047', src: 'images/photography/dscf1986_10.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '冬の道', title_en: 'Winter Road', title_zh: '冬之道',
    haiku_jp: '冬の道／霧の中から／列車来る',
    haiku_en: 'winter road — / out of the mist / a train approaches',
    haiku_zh: '冬之道／霧中／列車駛來' },
  { num: '046', src: 'images/photography/dscf1970_15.jpg', themes: ['yukiakari'], shape: 'landscape',
    title_jp: '冬の山', title_en: 'Winter Peak', title_zh: '冬山',
    haiku_jp: '雪の山／頂きにだけ／朝の紅',
    haiku_en: 'snowy peak — / only at its summit / morning crimson',
    haiku_zh: '雪山／僅在山巔／一抹晨紅' },
  { num: '029', src: 'images/photography/dscf9336.jpg', year: 2023, themes: ['kouyou'], shape: 'landscape',
    title_jp: '冬籠', title_en: 'Winter Hush', title_zh: '冬籠',
    haiku_jp: '冬籠り／軒下の影に／静けさあり',
    haiku_en: 'winter seclusion — / under the eaves\' shadow / there is stillness',
    haiku_zh: '冬籠／屋簷的陰影下／一片靜謐' },
  { num: '020', src: 'images/photography/dscf7306_xd2s.jpg', year: 2025, themes: ['yukiakari'], shape: 'landscape',
    title_jp: '雪明', title_en: 'Snow Light', title_zh: '雪明',
    haiku_jp: '雪明かり／闇の中にも／道はある',
    haiku_en: 'snow-light — / even within the dark / a path exists',
    haiku_zh: '雪明／黑暗之中／也有道路' },
  { num: '018', src: 'images/photography/dscf6254_15.jpg', year: 2025, themes: ['yukiakari'], shape: 'landscape',
    title_jp: '寒気', title_en: 'Cold Air', title_zh: '寒氣',
    haiku_jp: '寒気澄み／木立の間に／光ひとすじ',
    haiku_en: 'clear cold air — / among the trees / a thread of light',
    haiku_zh: '寒氣清澈／樹影之間／一線光明' },
  { num: '017', src: 'images/photography/dscf6254_10.jpg', year: 2025, themes: ['yukiakari'], shape: 'landscape',
    title_jp: '凍て野', title_en: 'Frozen Plain', title_zh: '凍野',
    haiku_jp: '凍て野や／風が描いて／消えてゆく',
    haiku_en: 'frozen plain — / what the wind draws / fades away',
    haiku_zh: '凍野／風所描畫／旋即消逝' },
  { num: '007', src: 'images/photography/dscf1023_11.jpg', year: 2025, themes: ['yukiakari'], shape: 'landscape',
    title_jp: '未明', title_en: 'Before Dawn', title_zh: '未明',
    haiku_jp: '未明や／凍てつく街に／灯ひとつ',
    haiku_en: 'before dawn — / in the freezing town / a single lamp',
    haiku_zh: '未明／凜冽的街頭／一盞燈火' },

  // ── 潮騒 TIDELINE ──
  { num: '011', src: 'images/photography/dscf4473_xd2s_9.jpg', year: 2026, themes: ['kaiyou'], shape: 'landscape',
    title_jp: '潮風', title_en: 'Sea Breeze', title_zh: '潮風',
    haiku_jp: '潮風や／髪を乱して／海光る',
    haiku_en: 'sea breeze — / tangling my hair / the ocean glints',
    haiku_zh: '潮風／撩亂髮絲／海面閃光' },
  { num: '122', src: 'images/photography/img_1272.jpg', themes: ['kaiyou','xpan'], shape: 'xpan',
    title_jp: '長き浜', title_en: 'Long Beach', title_zh: '長岸',
    haiku_jp: '長き浜／薄紅雲が／映りゆく',
    haiku_en: 'a long beach — / pale pink clouds / are mirrored',
    haiku_zh: '長長海岸／淡紅雲影／映於水中' },
  { num: '117', src: 'images/photography/dscf9938_2.jpg', themes: ['kaiyou','xpan'], shape: 'xpan',
    title_jp: '岩礁', title_en: 'The Reef', title_zh: '礁岩',
    haiku_jp: '冬の海／岩礁の松／一人立つ',
    haiku_en: 'winter sea — / the pine on the reef / stands alone',
    haiku_zh: '冬海／礁岩之松／獨自佇立' },
  { num: '052', src: 'images/photography/dscf2610.jpg', themes: ['kaiyou','xpan'], shape: 'xpan',
    title_jp: '紫の浜', title_en: 'Purple Shore', title_zh: '紫色海岸',
    haiku_jp: '紫の／浜辺に映る／空の色',
    haiku_en: 'on the purple shore / reflected — / the color of the sky',
    haiku_zh: '紫色海岸／映出／天的顏色' },
  { num: '138', src: 'images/photography/img_9610.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '柱と海', title_en: 'Pillar and Sea', title_zh: '柱與海',
    haiku_jp: '赤き柱／青き海原／白き雲',
    haiku_en: 'red pillars / blue ocean / white clouds',
    haiku_zh: '紅柱／青海／白雲' },
  { num: '133', src: 'images/photography/img_7934.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '夕の浜', title_en: 'Dusk Shore', title_zh: '黃昏之岸',
    haiku_jp: '紫の／空と海とが／一つになる',
    haiku_en: 'violet — / sky and sea / become one',
    haiku_zh: '紫色／天與海／合而為一' },
  { num: '129', src: 'images/photography/img_3675.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '小石の浜', title_en: 'Pebbled Coast', title_zh: '礫石海岸',
    haiku_jp: '夕焼けて／小石の影が／伸びゆく',
    haiku_en: 'evening glow — / the shadows of pebbles / lengthen',
    haiku_zh: '夕燒／礫石的影／拉長' },
  { num: '128', src: 'images/photography/img_3671.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '石と紫', title_en: 'Stones in Violet', title_zh: '石與紫',
    haiku_jp: '紫の／海原に石が／浮かびおり',
    haiku_en: 'in the violet sea — / stones / float',
    haiku_zh: '紫色海原／石塊／浮現' },
  { num: '127', src: 'images/photography/img_3653.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '凪の海', title_en: 'Calm Sea', title_zh: '凪海',
    haiku_jp: '凪の海／石ひとつぶに／光宿る',
    haiku_en: 'calm sea — / on a single stone / a light is held',
    haiku_zh: '寂靜的海／在一顆石上／光寄宿' },
  { num: '119', src: 'images/photography/img_0630.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '紫の砂', title_en: 'Purple Sand', title_zh: '紫沙',
    haiku_jp: '夕暮れに／砂は紫に／溶けゆきぬ',
    haiku_en: 'in the dusk — / the sand dissolves / into purple',
    haiku_zh: '黃昏／沙融入／紫色之中' },
  { num: '113', src: 'images/photography/dscf9864_2.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '霧と岩', title_en: 'Mist and Rock', title_zh: '霧與岩',
    haiku_jp: '黄金の／霧の中より／岩浮かぶ',
    haiku_en: 'out of the golden mist — / a rock / emerges',
    haiku_zh: '金霧之中／岩石／浮現而出' },
  { num: '109', src: 'images/photography/dscf9822_6.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '黄金の縁', title_en: 'Golden Edge', title_zh: '金緣',
    haiku_jp: '波の縁／光に縁取られ／砂は影',
    haiku_en: 'edge of the wave / outlined in light — / the sand is shadow',
    haiku_zh: '浪之邊緣／鑲著光／沙是影' },
  { num: '073', src: 'images/photography/dscf4364_1.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '波と山', title_en: 'Wave and Mountain', title_zh: '波與山',
    haiku_jp: '波しぶき／立山もまた／霞の中',
    haiku_en: 'breaking wave — / Tateyama too / fades into mist',
    haiku_zh: '浪花／立山／也沒入薄霧' },
  { num: '070', src: 'images/photography/dscf4204_2.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '飛沫', title_en: 'Splash', title_zh: '飛濺',
    haiku_jp: '波の音／霊峰を隠す／白き飛沫',
    haiku_en: 'sound of waves — / hiding the sacred peak / a white spray',
    haiku_zh: '浪聲／遮蔽霊峰／一道白色飛濺' },
  { num: '067', src: 'images/photography/dscf3914_4.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '霧立つ', title_en: 'Mist Rising', title_zh: '霧起',
    haiku_jp: '霧の中／鳥が舞い／松立てり',
    haiku_en: 'inside the mist — / birds dance / the pine stands',
    haiku_zh: '霧之中／鳥群飛舞／松樹挺立' },
  { num: '066', src: 'images/photography/dscf3877_3.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '岩と松', title_en: 'Rock and Pine', title_zh: '岩與松',
    haiku_jp: '岩の上／一本の松が／立つ朝に',
    haiku_en: 'on the rock — / a single pine / standing at dawn',
    haiku_zh: '岩之上／一棵松／立於晨' },
  { num: '065', src: 'images/photography/dscf3866_1.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '雨晴海岸', title_en: 'Amaharashi Coast', title_zh: '雨晴海岸',
    haiku_jp: '黄金の／霧と立山の／彼方かな',
    haiku_en: 'golden mist — / and far beyond / the Tateyama range',
    haiku_zh: '金霧／與遙遠的／立山連峰' },
  { num: '045', src: 'images/photography/50078818986_4a033d7988_o.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '群青', title_en: 'Deep Blue', title_zh: '群青',
    haiku_jp: '群青や／海と空との／境のなき',
    haiku_en: 'deep blue — / between sea and sky / no boundary',
    haiku_zh: '群青／海與天／無界' },
  { num: '044', src: 'images/photography/50078816876_d46a93535d_o.jpg', themes: ['kaiyou'], shape: 'landscape',
    title_jp: '雲の海', title_en: 'Cloud over Sea', title_zh: '雲海',
    haiku_jp: '海の上／雲が低くて／灰の朝',
    haiku_en: 'over the sea — / clouds hang low / a grey morning',
    haiku_zh: '海之上／雲低／灰色的早晨' },
  { num: '041', src: 'images/photography/img_9609.jpg', year: 2025, themes: ['kaiyou'], shape: 'landscape',
    title_jp: '漣', title_en: 'Ripples', title_zh: '漣漪',
    haiku_jp: '漣の／数を数えれば／夜になる',
    haiku_en: 'counting / the number of ripples — / night arrives',
    haiku_zh: '漣漪／數著數著／竟是夜了' },
  { num: '027', src: 'images/photography/dscf8513_2.jpg', year: 2025, themes: ['kaiyou'], shape: 'landscape',
    title_jp: '波音', title_en: 'Sound of Waves', title_zh: '波音',
    haiku_jp: '波音や／一人で歩く／浜の朝',
    haiku_en: 'sound of waves — / walking alone / a morning shore',
    haiku_zh: '波音／獨自漫步／晨之海濱' },
  { num: '024', src: 'images/photography/dscf8240_xd2s.jpg', year: 2025, themes: ['kaiyou'], shape: 'landscape',
    title_jp: '月の道', title_en: 'Path of the Moon', title_zh: '月之道',
    haiku_jp: '月の道／波の上にも／海の上にも',
    haiku_en: 'the moon\'s path — / on the waves / and on the sea',
    haiku_zh: '月之道／既在波上／也在海上' },
  { num: '053', src: 'images/photography/dscf2619.jpg', themes: ['kaiyou'], shape: 'square',
    title_jp: '紅の浜', title_en: 'Crimson Shore', title_zh: '紅之岸',
    haiku_jp: '夕焼けて／砂さえ赤く／染まりたる',
    haiku_en: 'evening glow — / even the sand / dyed crimson',
    haiku_zh: '夕陽染紅／連沙也／一片緋紅' },
  { num: '111', src: 'images/photography/dscf9843_1.jpg', themes: ['kaiyou'], shape: 'portrait',
    title_jp: '夕映え', title_en: 'Evening Glow', title_zh: '夕映',
    haiku_jp: '夕焼けて／岩礁の松も／黄金色',
    haiku_en: 'evening glow — / even the pine on the rock / turns to gold',
    haiku_zh: '夕陽燃燒／礁石上的松／也成了金色' },

  // ── 山水 LANDSCAPE ──
  { num: '030', src: 'images/photography/dscf9370_xd2s_3.jpg', year: 2025, themes: ['sansui','xpan'], shape: 'xpan',
    title_jp: '横長', title_en: 'Long View', title_zh: '橫長',
    haiku_jp: '横長に／切り取る景色／風の道',
    haiku_en: 'cut sideways — / the view becomes / a road for the wind',
    haiku_zh: '橫向裁切／所見之景／是風的道路' },
  { num: '064', src: 'images/photography/dscf3861_4.jpg', themes: ['sansui','xpan'], shape: 'xpan',
    title_jp: '富士と橋', title_en: 'Fuji and Bridge', title_zh: '富士與橋',
    haiku_jp: '黄昏や／橋の灯ともり／湖鎮まる',
    haiku_en: 'evening — / bridge lights come on / the lake stills',
    haiku_zh: '黃昏／橋燈亮起／湖面靜止' },
  { num: '057', src: 'images/photography/dscf3373_3.jpg', themes: ['sansui','xpan'], shape: 'xpan',
    title_jp: '富士暮', title_en: 'Fuji Dusk', title_zh: '富士暮',
    haiku_jp: '湖の上／富士の影に／街の灯',
    haiku_en: 'over the lake — / in Fuji\'s shadow / the city\'s lamps',
    haiku_zh: '湖之上／富士影下／城市之燈' },
  { num: '063', src: 'images/photography/dscf3839_3.jpg', themes: ['sansui','xpan'], shape: 'xpan',
    title_jp: '撮影者たち', title_en: 'The Photographers', title_zh: '攝影者群',
    haiku_jp: '夕暮れに／富士に向かいて／皆並ぶ',
    haiku_en: 'evening descends — / facing Mt Fuji / they all line up',
    haiku_zh: '黃昏／面向富士／眾人並排' },
  { num: '152', src: 'images/photography/img20260329_18543590.jpg', themes: ['sansui'], shape: 'landscape',
    title_jp: '舟列', title_en: 'Row of Boats', title_zh: '舟列',
    haiku_jp: '夕の湖／舟が静かに／一列なる',
    haiku_en: 'evening lake — / boats settle quietly / into a single line',
    haiku_zh: '湖之黃昏／舟靜靜地／排成一列' },
  { num: '101', src: 'images/photography/dscf7707_2.jpg', themes: ['sansui'], shape: 'landscape',
    title_jp: '水鏡', title_en: 'Water Mirror', title_zh: '水鏡',
    haiku_jp: '水鏡や／枯木の中の／冬の白',
    haiku_en: 'water mirror — / among the bare trees / winter white',
    haiku_zh: '水鏡／枯木之中／冬之白' },
  { num: '100', src: 'images/photography/dscf7649_1.jpg', themes: ['sansui'], shape: 'landscape',
    title_jp: '影と影', title_en: 'Shadow upon Shadow', title_zh: '影上之影',
    haiku_jp: '冬の湖／樹と樹影とが／溶け合う',
    haiku_en: 'winter lake — / tree and tree-shadow / melt into each other',
    haiku_zh: '冬湖／樹與樹影／彼此交融' },
  { num: '098', src: 'images/photography/dscf7472_2.jpg', themes: ['sansui'], shape: 'landscape',
    title_jp: '霧の樹', title_en: 'Tree in Mist', title_zh: '霧之樹',
    haiku_jp: '霧深く／一本の樹が／湖に立つ',
    haiku_en: 'deep mist — / a single tree / stands in the lake',
    haiku_zh: '霧氣深濃／一棵樹／立於湖中' },
  { num: '069', src: 'images/photography/dscf4128_1.jpg', themes: ['sansui'], shape: 'landscape',
    title_jp: '夏の華', title_en: 'Summer Bloom', title_zh: '夏之華',
    haiku_jp: '夏の夜／富士の上にも／華開く',
    haiku_en: 'summer night — / above Mt Fuji too / flowers bloom',
    haiku_zh: '夏夜／富士山上／也綻放著花' },
  { num: '022', src: 'images/photography/dscf7650_3.jpg', year: 2025, themes: ['sansui'], shape: 'landscape',
    title_jp: '静かな道', title_en: 'Quiet Path', title_zh: '靜謐之路',
    haiku_jp: '静けさや／道は林へ／吸い込まれ',
    haiku_en: 'such stillness — / the path is drawn / into the woods',
    haiku_zh: '靜謐／道路被林／緩緩吸入' },
  { num: '021', src: 'images/photography/dscf7430_1.jpg', year: 2025, themes: ['sansui'], shape: 'landscape',
    title_jp: '木立の道', title_en: 'Path through the Grove', title_zh: '林間之道',
    haiku_jp: '木立の奥／道はそのまま／光となる',
    haiku_en: 'deeper in the grove / the path itself / becomes light',
    haiku_zh: '林木深處／道路本身／化作光' },
  { num: '013', src: 'images/photography/dscf4989_xd3_1.jpg', year: 2025, themes: ['sansui'], shape: 'landscape',
    title_jp: '雲海', title_en: 'Sea of Clouds', title_zh: '雲海',
    haiku_jp: '合歓山や／雲海の上／朝の朱',
    haiku_en: 'Hehuanshan — / above the sea of clouds / dawn\'s vermilion',
    haiku_zh: '合歡山昆陽／雲海之上／晨之朱紅' },
  { num: '023', src: 'images/photography/dscf7974.jpg', year: 2025, themes: ['sansui'], shape: 'portrait',
    title_jp: '木洩日', title_en: 'Light through Trees', title_zh: '樹間之光',
    haiku_jp: '木の間より／光のこぼるる／午後の山',
    haiku_en: 'between the trees / light spills through — / afternoon hills',
    haiku_zh: '樹木之間／光斑灑落／午後群山' },

  // ── 街 STREET ──
  { num: '038', src: 'images/photography/img_8239.jpg', themes: ['street','xpan'], shape: 'xpan',
    title_jp: '横断', title_en: 'Crossing', title_zh: '橫渡',
    haiku_jp: '一線の／横断歩道を／風が抜く',
    haiku_en: 'a single line / the crosswalk / passes the wind',
    haiku_zh: '一線／斑馬線上／風穿過' },
  { num: '167', src: 'images/photography/r0008428.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '光の交差', title_en: 'Crossings of Light', title_zh: '光的交叉',
    haiku_jp: '光の中／二人の女の／別の道',
    haiku_en: 'in the light — / two women / on diverging paths',
    haiku_zh: '光中之間／兩位女子／各自的方向' },
  { num: '125', src: 'images/photography/img_3499.jpg', themes: ['street','xpan'], shape: 'xpan',
    title_jp: '世代', title_en: 'Generations', title_zh: '世代',
    haiku_jp: '古い時代の風を纏う老人と、新しい時代を生きる少女たち。台湾の街角は、こうして世代の距離を映し出す。',
    haiku_en: 'An old man carrying the air of another era, and girls living in a new age. Taiwan\'s street corners hold these generational distances side by side.',
    haiku_zh: '帶著舊時代氣息的老人，與生活在新時代的少女們。台灣的街角，就這樣映照出世代之間的距離。' },
  { num: '099', src: 'images/photography/dscf7531_1.jpg', themes: ['street','xpan'], shape: 'xpan',
    title_jp: '弱冷車', title_en: 'Mildly Cooled', title_zh: '弱冷車',
    haiku_jp: '車内に／凭れる影と／佇む影',
    haiku_en: 'inside the car — / one shadow leaning / one standing still',
    haiku_zh: '車廂內／倚靠的影／佇立的影' },
  { num: '040', src: 'images/photography/img_9439.jpg', year: 2025, themes: ['street','xpan'], shape: 'xpan',
    title_jp: '標語の下', title_en: 'Beneath the Slogan', title_zh: '標語之下',
    haiku_jp: '笑顔の広告の下を、身体に障害を持つ一人が静かに横切っていく。台湾の街は、こうした落差の上に成り立っている。',
    haiku_en: 'Beneath a smiling advertisement, a person with a disability quietly crosses the street. Taiwan\'s cities rest on gaps like these.',
    haiku_zh: '笑容滿面的廣告之下，一位身障者靜靜地穿越街道。台灣的城市，正建立在這樣的落差之上。' },
  { num: '151', src: 'images/photography/r0007238.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '電車にて', title_en: 'On the Train', title_zh: '車上',
    haiku_jp: '電車の中／三人並んで／眠る午後',
    haiku_en: 'on the train — / three of them in a row / a sleeping afternoon',
    haiku_zh: '電車裡／三人並排／午後的睡眠' },
  { num: '149', src: 'images/photography/l1005682_1.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '暖簾', title_en: 'Noren Curtain', title_zh: '暖簾',
    haiku_jp: '暖簾下／少女が一瞬／立ち止まる',
    haiku_en: 'beneath the noren — / for one moment / a girl stops',
    haiku_zh: '暖簾之下／少女一瞬／停下腳步' },
  { num: '148', src: 'images/photography/l1005040_2.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '老ひとり', title_en: 'An Elder Alone', title_zh: '老者獨行',
    haiku_jp: '宵の路地／老人の影が／振り返る',
    haiku_en: 'twilight alley — / an old man\'s shadow / turns around',
    haiku_zh: '黃昏小巷／老人的身影／回望' },
  { num: '147', src: 'images/photography/l1005020_2.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '町家', title_en: 'Old Town House', title_zh: '町家',
    haiku_jp: '瓦の下／白いキャップが／通り過ぐ',
    haiku_en: 'beneath the tiles — / a white cap / passes by',
    haiku_zh: '瓦下／一頂白帽／走過' },
  { num: '146', src: 'images/photography/l1004616_1.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '青き縞', title_en: 'Blue Stripes', title_zh: '藍條紋',
    haiku_jp: '青き縞／影の中をゆく／一人かな',
    haiku_en: 'blue stripes — / one figure walks / through the shadow',
    haiku_zh: '藍色條紋／一人／走過陰影' },
  { num: '144', src: 'images/photography/l1001209.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '地下道', title_en: 'Underpass', title_zh: '地下道',
    haiku_jp: '駅構内、誰の視線も届かない場所で、一人の暮らしが続いている。',
    haiku_en: 'Inside the station, in a place no gaze reaches, someone\'s life continues.',
    haiku_zh: '車站內部，在無人投以目光的角落，有一個人的生活，仍在繼續。' },
  { num: '143', src: 'images/photography/l1001068.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '市場の昼', title_en: 'Market Noon', title_zh: '市場午後',
    haiku_jp: '市場の隅／一瞬の休み／影に潜む',
    haiku_en: 'corner of the market — / a single instant of rest / hidden in shadow',
    haiku_zh: '市場一隅／片刻的歇息／藏在陰影裡' },
  { num: '142', src: 'images/photography/l1000839.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '夜の屋台', title_en: 'Night Stall', title_zh: '夜屋台',
    haiku_jp: '夜の街／灯ひとつ点り／湯気が立つ',
    haiku_en: 'in the night — / one light comes on / steam rises',
    haiku_zh: '夜街／一盞燈亮起／蒸氣升騰' },
  { num: '141', src: 'images/photography/l1000757.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '東屋', title_en: 'Pavilion', title_zh: '亭中',
    haiku_jp: '夏の午後／東屋の影に／皆ひとり',
    haiku_en: 'summer afternoon / in the pavilion\'s shade / each one alone',
    haiku_zh: '夏日午後／亭子的陰影下／各自一人' },
  { num: '140', src: 'images/photography/l1000737.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '老姉妹', title_en: 'Elder Sisters', title_zh: '老姐妹',
    haiku_jp: '昼下がり／三人の影が／同じ風',
    haiku_en: 'mid-afternoon — / three shadows share / the same breeze',
    haiku_zh: '午後／三個身影／同一陣風' },
  { num: '139', src: 'images/photography/l1000612.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '搬運', title_en: 'Conveyance', title_zh: '搬運',
    haiku_jp: '空港の／エスカレーター／世界の脈',
    haiku_en: 'at the airport — / the escalator carries / the pulse of the world',
    haiku_zh: '機場／電扶梯／載著世界的脈搏' },
  { num: '121', src: 'images/photography/img_0843.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '滑り台', title_en: 'Empty Slide', title_zh: '溜滑梯',
    haiku_jp: '子ども用の遊具に囲まれて、車椅子の老婦人が一人坐っている。台湾の高齢化と少子化が、同じ風景の中で出会う。',
    haiku_en: 'Surrounded by children\'s playground equipment, an elderly woman sits alone in her wheelchair. Taiwan\'s aging and birth-decline meet in a single landscape.',
    haiku_zh: '在兒童遊具的環抱中，一位老婦人獨自坐在輪椅上。台灣的高齡化與少子化，在同一個畫面裡相遇。' },
  { num: '120', src: 'images/photography/img_0794.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '線香', title_en: 'Incense Stick', title_zh: '線香',
    haiku_jp: '煙立ち／祈りは音も／立てぬまま',
    haiku_en: 'rising smoke — / a prayer / makes no sound',
    haiku_zh: '香煙升起／祈禱／默默無聲' },
  { num: '106', src: 'images/photography/dscf8066.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '空を飛びたい', title_en: 'I Wish to Fly', title_zh: '想要飛翔',
    haiku_jp: '未明の街角、銀行の「空を飛びたい」と謳う広告の下で、廃品を拾う一人の老人が腰を下ろしている。広告の約束する自由と、深夜の街を歩く現実は、こんなにも遠い。',
    haiku_en: 'At pre-dawn on a street corner, beneath a bank ad proclaiming \'I wish to fly!\', an elderly scavenger sits down to rest. The freedom an advertisement promises, and the reality of walking pre-dawn streets, are this far apart.',
    haiku_zh: '凌晨的街角，在銀行「想要飛翔」的廣告下方，一位拾荒老人坐下歇息。廣告所許諾的自由，與深夜行走街頭的現實，竟是這般遙遠。' },
  { num: '104', src: 'images/photography/dscf7924.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '昼休み', title_en: 'Midday Rest', title_zh: '午歇',
    haiku_jp: '昼下がり／壁にもたれて／足を上げる',
    haiku_en: 'mid-afternoon — / against the wall, he lifts / one tired foot',
    haiku_zh: '正午過後／靠著牆／抬起疲倦的腳' },
  { num: '048', src: 'images/photography/dscf2182_2.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '光と影', title_en: 'Light and Shadow', title_zh: '光與影',
    haiku_jp: '光の縞／影と影の／間に人',
    haiku_en: 'stripes of light — / between shadow and shadow / a single figure',
    haiku_zh: '光的條紋／在影與影之間／一個身影' },
  { num: '014', src: 'images/photography/dscf5216.jpg', year: 2016, themes: ['street'], shape: 'landscape',
    title_jp: '平日', title_en: 'A Weekday', title_zh: '平日',
    haiku_jp: '平日の／通りに昼の／沈黙あり',
    haiku_en: 'on a weekday / a quiet noon settles into / the empty street',
    haiku_zh: '平日／通街上／中午的沉默' },
  { num: '006', src: 'images/photography/dsc_1606.jpg', year: 2025, themes: ['street'], shape: 'landscape',
    title_jp: '光の縞', title_en: 'Stripes of Light', title_zh: '光線',
    haiku_jp: '光の縞／子の声と共に／走り去る',
    haiku_en: 'stripes of summer light / running away with / a child\'s laughter',
    haiku_zh: '光的縞／伴著孩童的笑聲／奔跑而去' },
  { num: '004', src: 'images/photography/51897012615_d1c1380f41_o.jpg', year: 2017, themes: ['street'], shape: 'landscape',
    title_jp: '夕河', title_en: 'Riverside Dusk', title_zh: '河畔暮色',
    haiku_jp: '暮れ方の／河面に映る／街の灯',
    haiku_en: 'evening tide / the river surface holds / the city\'s lamps',
    haiku_zh: '黃昏／河面映出／城市的燈' },
  { num: '001', src: 'images/photography/1559799148756.jpg', year: 2016, themes: ['street'], shape: 'landscape',
    title_jp: '鏡像', title_en: 'Mirror', title_zh: '鏡像',
    haiku_jp: '街角に／別の人生が／すれ違う',
    haiku_en: 'at the street corner / two lives brush past each other / never meeting',
    haiku_zh: '街角／兩個人生／擦身而過' },
  { num: '135', src: 'images/photography/img_8528.jpg', themes: ['street'], shape: 'square',
    title_jp: '路傍', title_en: 'Roadside', title_zh: '路旁',
    haiku_jp: '路傍にて／煙のかたち／光になる',
    haiku_en: 'by the roadside / the shape of smoke / becomes light',
    haiku_zh: '路旁／煙之形／成為光' },
  { num: '039', src: 'images/photography/img_9437.jpg', year: 2025, themes: ['street'], shape: 'square',
    title_jp: '角', title_en: 'The Corner', title_zh: '街角',
    haiku_jp: '角を曲がる／一秒の前と／一秒の後',
    haiku_en: 'turning the corner / one second before / one second after',
    haiku_zh: '轉角／一秒之前／一秒之後' },
  { num: '034', src: 'images/photography/img_3503_2.jpg', year: 2024, themes: ['street'], shape: 'square',
    title_jp: '街の影', title_en: 'City Shadow', title_zh: '街影',
    haiku_jp: '影が影に／重なるとき／街は静か',
    haiku_en: 'when shadow overlaps shadow / the city / falls silent',
    haiku_zh: '影與影／互相重疊／街正寂靜' },
  { num: '137', src: 'images/photography/img_9432.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '広告の下', title_en: 'Beneath the Ad', title_zh: '廣告之下',
    haiku_jp: '若く美しいモデルの広告の真下で、一人の老人が荷物とともに座り込んでいる。広告が約束する未来と、街が抱える現実は、別物のままだ。',
    haiku_en: 'Right beneath an ad featuring beautiful young models, an old man sits with his belongings. The future an advertisement promises, and the reality a city carries, remain different things.',
    haiku_zh: '在年輕貌美模特兒的廣告正下方，一位老人帶著家當坐著。廣告所承諾的未來，與城市承載的現實，始終是兩件不同的事。' },
  { num: '134', src: 'images/photography/img_8520.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '一服', title_en: 'A Smoke Break', title_zh: '一根菸',
    haiku_jp: '煙の中／一人だけの／時間ある',
    haiku_en: 'inside the smoke — / a private fragment / of time',
    haiku_zh: '煙之中／屬於一個人的／時光' },
  { num: '131', src: 'images/photography/img_3775.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '少年神', title_en: 'Boy God', title_zh: '少年神',
    haiku_jp: '少年の／顔に神の名が／描かれぬ',
    haiku_en: 'on a boy\'s face / the name of a god / has been painted',
    haiku_zh: '少年的臉上／神之名／已被勾勒' },
  { num: '130', src: 'images/photography/img_3771.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '神將', title_en: 'Spirit Walker', title_zh: '神將',
    haiku_jp: '化粧して／神になる午後／祭の街',
    haiku_en: 'painted face — / becoming a god, this afternoon / the festival street',
    haiku_zh: '臉上彩繪／午後化身為神／祭典之街' },
  { num: '124', src: 'images/photography/img_2766.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '自転車', title_en: 'Bicycle', title_zh: '自行車',
    haiku_jp: '自転車の／影が長くなる／夕の街',
    haiku_en: 'on the bicycle / shadows lengthen — / dusk in the city',
    haiku_zh: '自行車的／影子拉長／黃昏的街' },
  { num: '123', src: 'images/photography/img_2765.jpg', themes: ['street'], shape: 'portrait',
    title_jp: '着物の人', title_en: 'Woman in Kimono', title_zh: '著和服的人',
    haiku_jp: '車椅子／押す老婦人／街の朝',
    haiku_en: 'pushing her cart — / an old woman in kimono / morning street',
    haiku_zh: '推著車／著和服的老婦人／晨之街' },
  { num: '033', src: 'images/photography/img_2893.jpg', year: 2024, themes: ['street'], shape: 'portrait',
    title_jp: '路地', title_en: 'The Alley', title_zh: '巷弄',
    haiku_jp: '名もなき／路地に立ち止まる／旅の足',
    haiku_en: 'a nameless alley / where the traveler\'s feet / decide to pause',
    haiku_zh: '無名的巷弄／旅人的腳步／在此停下' },

  { num: '164', src: 'images/photography/dscf6955.jpg', themes: ['street'], shape: 'landscape',
    title_jp: '財の影に', title_en: 'Beneath the Promise', title_zh: '財富之下',
    haiku_jp: '広告の／豊かな手の下／一つの命',
    haiku_en: 'under the billboard\'s / abundant hands — / a single life',
    haiku_zh: '看板的／豐饒之手下／一個人生' },

  // ── Xpan 65×24 ──
  { num: '108', src: 'images/photography/dscf9714_1.jpg', themes: ['xpan','sansui'], shape: 'xpan',
    title_jp: '雪解水', title_en: 'Snowmelt', title_zh: '雪解之水',
    haiku_jp: '冬の湖／光の島が／浮かびおり',
    haiku_en: 'winter lake — / an island of light / floats',
    haiku_zh: '冬湖／光的島嶼／漂浮其上' },
  { num: '031', src: 'images/photography/dscf9616_3.jpg', year: 2022, themes: ['xpan'], shape: 'xpan',
    title_jp: '遥か', title_en: 'Far Horizon', title_zh: '遙遠',
    haiku_jp: '遥かなる／水平線の／その向こう',
    haiku_en: 'far horizon — / and beyond it / what?',
    haiku_zh: '遙遠的／水平線／那一邊呢' },

  // ── 銀塩 GINEN ──
  { num: '153', src: 'images/photography/img20260328_12583059.jpg', themes: ['kaiyou','ginen'], shape: 'square',
    title_jp: '夕渚', title_en: 'Twilight Shore', title_zh: '黃昏渚',
    haiku_jp: '夕暮れの／岩を撫でゆく／海の息',
    haiku_en: 'evening tide / brushing past the rocks — / the sea\'s breathing',
    haiku_zh: '黃昏潮／撫過礁岩／是海的呼吸' },
  { num: '154', src: 'images/photography/img20260328_23413131.jpg', themes: ['harugasumi','ginen'], shape: 'landscape',
    title_jp: '空の桜', title_en: 'Sky Cherries', title_zh: '天上之櫻',
    haiku_jp: '青空に／桜浮かびて／春深し',
    haiku_en: 'against the blue / cherry petals float — / spring at full depth',
    haiku_zh: '藍天之上／櫻浮其間／春日深濃' },
  { num: '155', src: 'images/photography/img20260329_00015264.jpg', themes: ['street','ginen'], shape: 'landscape',
    title_jp: '段の朝', title_en: 'Curve and Conversation', title_zh: '弧形階梯',
    haiku_jp: '光の段／二人の影が／世界をなす',
    haiku_en: 'curving steps of light / two shadows / make a world',
    haiku_zh: '光之階／兩人影下／自成世界' },
  { num: '156', src: 'images/photography/img20260329_18322903-4.jpg', themes: ['sansui','ginen'], shape: 'landscape',
    title_jp: '霞む嶺', title_en: 'Layered Ridges', title_zh: '疊嶺',
    haiku_jp: '幾重にも／山が遠ざかり／霧となる',
    haiku_en: 'layer upon layer / mountains receding / into mist',
    haiku_zh: '山疊山／逐層退遠／化作霧' },
  { num: '157', src: 'images/photography/img20260329_18342827-3.jpg', themes: ['kaiyou','ginen'], shape: 'portrait',
    title_jp: '紫の渚', title_en: 'Violet Shore', title_zh: '紫渚',
    haiku_jp: '紫の／砂の上には／石ばかり',
    haiku_en: 'on the violet sand — / nothing but stones / waiting',
    haiku_zh: '紫色砂上／盡是石頭／靜靜等待' },
  { num: '158', src: 'images/photography/img20260329_18364620.jpg', themes: ['harugasumi','ginen'], shape: 'landscape',
    title_jp: '白桜', title_en: 'White Cherry', title_zh: '白櫻',
    haiku_jp: '白桜／葉の若さに／風通る',
    haiku_en: 'white cherry — / through the youth of leaves / wind passes',
    haiku_zh: '白櫻／嫩葉之間／有風吹過' },
  { num: '159', src: 'images/photography/img20260329_18390699.jpg', themes: ['sansui','ginen'], shape: 'landscape',
    title_jp: '夜明けの桟橋', title_en: 'Dawn Pier', title_zh: '黎明棧橋',
    haiku_jp: '湖の朝／舟の集まる／木の桟橋',
    haiku_en: 'morning lake — / boats gathered at / a wooden pier',
    haiku_zh: '湖之晨／船舟聚於／木造棧橋' },
  { num: '160', src: 'images/photography/img20260329_18432078.jpg', themes: ['kaiyou','ginen'], shape: 'portrait',
    title_jp: '海辺の鐘楼', title_en: 'Belltower by the Sea', title_zh: '海邊的鐘塔',
    haiku_jp: '夕の海／鐘楼の灯／一つだけ',
    haiku_en: 'evening sea — / from the belltower / a single lit window',
    haiku_zh: '黃昏之海／鐘塔之中／一盞燈光' },
  { num: '161', src: 'images/photography/img20260329_18453446.jpg', themes: ['sansui','ginen'], shape: 'landscape',
    title_jp: '霧の谷', title_en: 'Misted Slope', title_zh: '霧之谷',
    haiku_jp: '逆光の／木々の間より／霧が湧く',
    haiku_en: 'against the light / between the trees / mist wells up',
    haiku_zh: '逆光之中／樹木之間／霧氣升起' },
  { num: '162', src: 'images/photography/img20260329_18570039.jpg', themes: ['harugasumi','ginen'], shape: 'landscape',
    title_jp: '虹をくぐる花', title_en: 'Cherry through Rainbow', title_zh: '虹下之花',
    haiku_jp: '白い花／虹の帯と／一緒に咲く',
    haiku_en: 'white blossoms / and a band of rainbow / blooming together',
    haiku_zh: '白花綻放／與虹之光帶／同時生長' },
  { num: '163', src: 'images/photography/img20260329_21545333.jpg', themes: ['sansui','ginen'], shape: 'landscape',
    title_jp: '原の樹', title_en: 'Tree on the Plain', title_zh: '原野之樹',
    haiku_jp: '一本の／樹を残しつつ／遠い山',
    haiku_en: 'leaving / one tree behind — / the distant mountains',
    haiku_zh: '留下／一棵孤樹／遠方有山' },

];
